### PR TITLE
Change bootstraap server to localhost:9093

### PR DESCRIPTION
**Pull request by najmabad**
This is correct in the video but still not updated here.

### CODE REVIEW

**Comment by najmabad** [comment]
@team-data-science do you want to merge this?

**Comment by najmabad** [comment]
@team-data-science do you want to merge this?

**Comment by team-data-science** [comment]
Thanks Najma!! I'merged it

**Comment by najmabad** [comment]
Actually, after a few videos, you change it back to kafka:9092 as I imagine this is needed when the API app is moved to the container. So I think that this was correct. Maybe you could add a comment to change it to localhost:9093 when the API is local.

**Comment by team-data-science** [comment]
Arrgh :D

**Comment by team-data-science** [comment]
I reverted it

**Pull request merged**
